export const restaurants = [
  {
    id: "1",
    name: "La Brasserie del Mar",
    city: "Barcelona",
    neighborhood: "Barceloneta",
    cuisineCategory: "Mediterranea",
    cuisine: "Mediterranea",
    tags: ["Mariscos", "Terraza", "Romantico"],
    rating: 4.7,
    reviewCount: 234,
    priceRange: 3,
    verifiedOnly: true,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
    address: "Calle Marina 42, Barceloneta, Barcelona",
    description: "Cocina mediterranea de autor con los mejores mariscos frescos del dia. Terraza con vistas al puerto.",
    openHours: "13:00 - 23:30",
    phone: "+34 932 456 789",
    instagram: "@labrasseriedelmar",
    website: "https://labrasseriedelmar.es",
    cancellationPolicy: "Cancelacion gratuita hasta 4 horas antes de la reserva.",
    verified: true,
    reservationsThisMonth: 87,
    benefit: "Postre gratis en tu proxima visita",
    menu: [
      { name: "Tartar de atun rojo", price: 18, category: "Entrantes" },
      { name: "Croquetas de jamon iberico", price: 12, category: "Entrantes" },
      { name: "Paella de marisco (2 pax)", price: 38, category: "Principales" },
      { name: "Lubina a la sal", price: 28, category: "Principales" },
      { name: "Gambas al ajillo", price: 16, category: "Principales" },
      { name: "Tiramisú de limon", price: 9, category: "Postres" },
      { name: "Crema catalana", price: 8, category: "Postres" },
    ],
  },
  {
    id: "2",
    name: "Sakura Ramen House",
    city: "Barcelona",
    neighborhood: "Eixample",
    cuisineCategory: "Japonesa",
    cuisine: "Japonesa",
    tags: ["Ramen", "Casual", "Rapido"],
    rating: 4.5,
    reviewCount: 187,
    priceRange: 2,
    verifiedOnly: true,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    address: "Av. Diagonal 156, Eixample, Barcelona",
    description: "Autentico ramen japones preparado con caldos cocinados durante 18 horas. Ambiente acogedor.",
    openHours: "12:00 - 22:00",
    phone: "+34 933 111 222",
    instagram: "@sakuraramen",
    website: "https://sakuraramen.es",
    cancellationPolicy: "Cancelacion gratuita hasta 2 horas antes.",
    verified: true,
    reservationsThisMonth: 145,
    benefit: "Café de cortesia en tu proxima visita",
    menu: [
      { name: "Tonkotsu Ramen", price: 14, category: "Ramen" },
      { name: "Shoyu Ramen", price: 13, category: "Ramen" },
      { name: "Miso Ramen", price: 13, category: "Ramen" },
      { name: "Gyozas (6 uds)", price: 8, category: "Entrantes" },
      { name: "Edamame", price: 5, category: "Entrantes" },
      { name: "Mochi helado (3 uds)", price: 7, category: "Postres" },
    ],
  },
  {
    id: "3",
    name: "El Fogon de la Abuela",
    city: "Madrid",
    neighborhood: "Centro",
    cuisineCategory: "Tradicional",
    cuisine: "Tradicional",
    tags: ["Casero", "Familiar", "Menu del dia"],
    rating: 4.8,
    reviewCount: 412,
    priceRange: 1,
    verifiedOnly: true,
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&h=400&fit=crop",
    address: "Plaza Mayor 8, Centro, Madrid",
    description: "Recetas de toda la vida con productos de temporada. El mejor cocido madrileno de la ciudad.",
    openHours: "12:30 - 16:00, 20:00 - 23:00",
    phone: "+34 915 678 901",
    instagram: "@elfogondelaabuela",
    website: "https://elfogondelaabuela.es",
    cancellationPolicy: "Cancelacion gratuita hasta 6 horas antes. Grupos de mas de 6 personas requieren 24h de antelacion.",
    verified: true,
    reservationsThisMonth: 210,
    menu: [
      { name: "Cocido madrileno completo", price: 18, category: "Principales" },
      { name: "Callos a la madrilena", price: 14, category: "Principales" },
      { name: "Chuleton de Avila", price: 28, category: "Principales" },
      { name: "Sopa castellana", price: 8, category: "Entrantes" },
      { name: "Ensalada de la huerta", price: 9, category: "Entrantes" },
      { name: "Torrijas de la abuela", price: 6, category: "Postres" },
      { name: "Arroz con leche", price: 5, category: "Postres" },
    ],
  },
  {
    id: "4",
    name: "Nomada Brunch & Co",
    city: "Madrid",
    neighborhood: "Malasana",
    cuisineCategory: "Brunch",
    cuisine: "Brunch",
    tags: ["Brunch", "Vegano", "Instagrameable"],
    rating: 4.3,
    reviewCount: 156,
    priceRange: 2,
    verifiedOnly: false,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
    address: "Calle Fuencarral 78, Malasana, Madrid",
    description: "Brunch creativo con opciones veganas y sin gluten. Zumos cold-pressed y cafe de especialidad.",
    openHours: "09:00 - 17:00",
    phone: "+34 916 234 567",
    instagram: "@nomadabrunch",
    website: "https://nomadabrunch.com",
    cancellationPolicy: "Cancelacion gratuita hasta 2 horas antes.",
    verified: false,
    reservationsThisMonth: 62,
    menu: [
      { name: "Avocado toast con huevo poche", price: 12, category: "Brunch" },
      { name: "Tortitas de ricotta con berries", price: 11, category: "Brunch" },
      { name: "Acai bowl", price: 10, category: "Bowls" },
      { name: "Huevos benedictinos", price: 13, category: "Brunch" },
      { name: "Zumo green detox", price: 6, category: "Bebidas" },
      { name: "Flat white", price: 4, category: "Bebidas" },
    ],
  },
  {
    id: "5",
    name: "Trattoria da Marco",
    city: "Barcelona",
    neighborhood: "Gracia",
    cuisineCategory: "Italiana",
    cuisine: "Italiana",
    tags: ["Pasta", "Pizza", "Vino"],
    rating: 4.6,
    reviewCount: 298,
    priceRange: 2,
    verifiedOnly: true,
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&h=400&fit=crop",
    address: "Carrer de Valencia 210, Gracia, Barcelona",
    description: "Autentica cocina italiana con pasta fresca hecha a mano cada dia. Carta de vinos selecta.",
    openHours: "13:00 - 00:00",
    phone: "+34 934 567 890",
    instagram: "@trattoriadamarco",
    website: "https://trattoriadamarco.es",
    cancellationPolicy: "Cancelacion gratuita hasta 3 horas antes de la reserva.",
    verified: true,
    reservationsThisMonth: 178,
    menu: [
      { name: "Burrata con tomate", price: 14, category: "Entrantes" },
      { name: "Carpaccio de ternera", price: 16, category: "Entrantes" },
      { name: "Tagliatelle al ragu", price: 15, category: "Pasta" },
      { name: "Risotto ai funghi porcini", price: 17, category: "Pasta" },
      { name: "Pizza Margherita", price: 12, category: "Pizza" },
      { name: "Tiramisu della casa", price: 8, category: "Postres" },
      { name: "Panna cotta", price: 7, category: "Postres" },
    ],
  },
  {
    id: "6",
    name: "Tandoori Palace",
    city: "Madrid",
    neighborhood: "Chamberi",
    cuisineCategory: "India",
    cuisine: "India",
    tags: ["Curry", "Especias", "Buffet"],
    rating: 4.4,
    reviewCount: 178,
    priceRange: 2,
    verifiedOnly: true,
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&h=400&fit=crop",
    address: "Gran Via 45, Chamberi, Madrid",
    description: "Los mejores curries y tandooris de la ciudad. Buffet de fin de semana con mas de 30 platos.",
    openHours: "12:00 - 23:30",
    phone: "+34 917 890 123",
    instagram: "@tandooripalace",
    website: "https://tandooripalace.es",
    cancellationPolicy: "Cancelacion gratuita hasta 4 horas antes. No show se cobrara un deposito de 10EUR por persona.",
    verified: true,
    reservationsThisMonth: 95,
    menu: [
      { name: "Samosas de verduras (4 uds)", price: 7, category: "Entrantes" },
      { name: "Pakora mixta", price: 8, category: "Entrantes" },
      { name: "Chicken Tikka Masala", price: 14, category: "Principales" },
      { name: "Lamb Rogan Josh", price: 16, category: "Principales" },
      { name: "Palak Paneer", price: 12, category: "Principales" },
      { name: "Naan bread", price: 3, category: "Acompanantes" },
      { name: "Gulab Jamun", price: 6, category: "Postres" },
    ],
  },
];

export const reservations = [
  {
    id: "res-1",
    restaurantId: "1",
    date: "2026-02-14",
    time: "21:00",
    guests: 2,
    status: "CONFIRMED",
    notes: "Aniversario, mesa junto a la ventana si es posible",
    reviewed: false,
  },
  {
    id: "res-2",
    restaurantId: "3",
    date: "2026-02-10",
    time: "14:00",
    guests: 4,
    status: "COMPLETED",
    notes: "",
    reviewed: true,
  },
  {
    id: "res-3",
    restaurantId: "5",
    date: "2026-02-08",
    time: "20:30",
    guests: 3,
    status: "COMPLETED",
    notes: "Alergias: gluten",
    reviewed: false,
  },
  {
    id: "res-4",
    restaurantId: "2",
    date: "2026-02-20",
    time: "13:00",
    guests: 1,
    status: "PENDING_CONFIRMATION",
    notes: "",
    reviewed: false,
  },
  {
    id: "res-5",
    restaurantId: "4",
    date: "2026-01-28",
    time: "10:30",
    guests: 2,
    status: "COMPLETED",
    notes: "",
    reviewed: true,
  },
  {
    id: "res-6",
    restaurantId: "6",
    date: "2026-01-15",
    time: "20:00",
    guests: 5,
    status: "NO_SHOW",
    notes: "",
    reviewed: false,
  },
  {
    id: "res-7",
    restaurantId: "1",
    date: "2026-01-10",
    time: "14:00",
    guests: 2,
    status: "CANCELED",
    notes: "Cambio de planes",
    reviewed: false,
  },
];

export const reviews = [
  {
    id: "rev-1",
    reservationId: "res-2",
    restaurantId: "3",
    userId: "user-1",
    userName: "Maria G.",
    rating: 5,
    comment: "El mejor cocido que he probado en anos. Servicio impecable y ambiente muy acogedor. Repetire seguro.",
    date: "2026-02-10",
    verified: true,
    categories: {
      food: 5,
      service: 5,
      ambiance: 4,
      value: 5,
    },
  },
  {
    id: "rev-2",
    reservationId: "res-5",
    restaurantId: "4",
    userId: "user-1",
    userName: "Maria G.",
    rating: 4,
    comment: "Brunch muy bueno, las tortitas de ricotta son increibles. Un poco de espera pero merece la pena.",
    date: "2026-01-28",
    verified: true,
    categories: {
      food: 5,
      service: 3,
      ambiance: 5,
      value: 4,
    },
  },
  {
    id: "rev-3",
    reservationId: "res-ext-1",
    restaurantId: "1",
    userId: "user-2",
    userName: "Carlos R.",
    rating: 4,
    comment: "Marisco fresco y bien preparado. La terraza es maravillosa al atardecer. Precios algo elevados.",
    date: "2026-02-05",
    verified: true,
    categories: {
      food: 5,
      service: 4,
      ambiance: 5,
      value: 3,
    },
  },
  {
    id: "rev-4",
    reservationId: "res-ext-2",
    restaurantId: "2",
    userId: "user-3",
    userName: "Ana L.",
    rating: 5,
    comment: "El tonkotsu ramen es de los mejores fuera de Japon. Perfecto para dias frios. Volveremos!",
    date: "2026-01-20",
    verified: true,
    categories: {
      food: 5,
      service: 4,
      ambiance: 4,
      value: 5,
    },
  },
  {
    id: "rev-5",
    reservationId: "res-ext-3",
    restaurantId: "5",
    userId: "user-4",
    userName: "Pedro M.",
    rating: 4,
    comment: "Pasta al dente perfecta. El tiramisú es espectacular. Buen servicio aunque algo lento en hora punta.",
    date: "2026-02-01",
    verified: true,
    categories: {
      food: 5,
      service: 3,
      ambiance: 4,
      value: 4,
    },
  },
  {
    id: "rev-6",
    reservationId: "res-ext-4",
    restaurantId: "1",
    userId: "user-5",
    userName: "Laura T.",
    rating: 5,
    comment: "Una experiencia gastronomica excepcional. El tartar de atun y la paella, de 10. Volvere sin duda.",
    date: "2026-01-15",
    verified: true,
    categories: {
      food: 5,
      service: 5,
      ambiance: 5,
      value: 4,
    },
  },
  {
    id: "rev-7",
    reservationId: "res-ext-5",
    restaurantId: "3",
    userId: "user-6",
    userName: "Javier S.",
    rating: 4,
    comment: "Las croquetas de jamon son espectaculares. Buen trato familiar. El cocido necesita algo mas de sal.",
    date: "2026-01-08",
    verified: true,
    categories: {
      food: 4,
      service: 5,
      ambiance: 4,
      value: 5,
    },
  },
];

export const timeSlots = [
  "12:00", "12:30", "13:00", "13:30", "14:00", "14:30",
  "15:00", "19:00", "19:30", "20:00", "20:30", "21:00",
  "21:30", "22:00", "22:30",
];

export const cuisineFilters = [
  "Todos",
  "Mediterranea",
  "Japonesa",
  "Tradicional",
  "Italiana",
  "India",
  "Brunch",
];

export const currentUser = {
  id: "user-1",
  name: "Maria Garcia",
  email: "maria@example.com",
  avatar: "/avatar.jpg",
  memberSince: "2025-06-15",
  totalReservations: 23,
  totalReviews: 12,
  favoriteRestaurants: ["1", "3", "5"],
};
